{{- if .Values.secret.enabled  }}
apiVersion: v1 
kind: Sercrt
metadata:
  name: {{ include "employeeapp.name" . }}
  namespace: {{ include "employeeapp.namespace" . }}
type: Opaque 
stringData:
{{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value }}
{{- end }}  
{{- end }}